---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-backup.fullname" . }}
  labels:
    {{- include "github-backup.labels" . | nindent 4 }}
data:
  {{- if .Values.token }}
  token: {{ .Values.token | b64enc }}
  {{- end }}
  {{- if .Values.id_rsa }}
  id_rsa: {{ .Values.id_rsa | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-backup.fullname" . }}-aws
  labels:
    {{- include "github-backup.labels" . | nindent 4 }}
stringData:
  credentials: |
    [default]
    aws_access_key_id = {{ .Values.s3.accessKeyID }}
    aws_secret_access_key = {{ .Values.s3.secretAccessKey }}
  config: |
    [default]
    region = {{ .Values.s3.region }}
